spring:
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tt_custserv
    username: postgres
    password: 123
  flyway:
    enabled: true
    baselineOnMigrate: true